export const ROUTES = {
  PUBLIC: {
    HOME: '/',
    ABOUT: '/about',
    SERVICES: '/services',
    GALLERY: '/gallery',
    CONTACT: '/contact',
    FAQ: '/faq',
    REQUEST_QUOTE: '/request-quote',
  },
  ADMIN: {
    LOGIN: '/admin/login',
    ROOT: '/admin',
    DASHBOARD: '/admin/dashboard',
    BUSINESS: '/admin/business',
    HERO: '/admin/hero',
    ABOUT: '/admin/about',
    SERVICES: '/admin/services',
    WHY_AAA: '/admin/why-aaa',
    PROCESS: '/admin/process',
    GALLERY: '/admin/gallery',
    FAQS: '/admin/faqs',
    ENQUIRIES: '/admin/enquiries',
    QUOTE_REQUESTS: '/admin/quote-requests',
    PRICING: '/admin/pricing',
    QUOTATIONS: '/admin/quotations',
    SETTINGS: '/admin/settings',
  },
} as const;
